server {
    listen       80;
    listen       [::]:80;
    server_name  _;

    root   /usr/share/nginx/html;

    server_tokens off;

    location = /up {
        access_log off;
        return 200 "ok\n";
    }

    location = / {
        return 503;
    }
    error_page 503 /index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /font/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
